# Generated by Django 5.1 on 2024-10-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
